### ISSUE TITLE
Improvoment: Memory management.

### ISSUE THREAD

**Issue by nanoric** [MochanShrestha/accumulatorplus#1]
I found your project great!
And i'm going to add memory management (allocator) support to this library.
Before I started coding, It maybe necessary for me to know if you are still maintaining this project? 
If so I will create some PR to this project.

**Comment by MochanShrestha** [comment]
Hi. You can submit pull request. I haven't worked on it for a while. I meant to extend it in a lot of ways but have been busy,  

If the project is useful, please submit a pull request and will request.

Let me know if you have any questions as well.

**Comment by nanoric** [comment]
I finally find that boost.accumulator does'nt fit my requirements. Extending it is too hard: Components  can't be reused.
So I'm going to write a new accumulator library. Maybe not as good as boost.accumulator, but should fit my requirements.
